# NLP -> Natural Language Processing

In [2]:
import numpy as np
import pandas as pd

In [10]:
df = pd.read_csv("Day 14 dataset\\IMDB Dataset.csv")

In [11]:
df.head(5)

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [12]:
df['review'][3]

"Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br /><br />OK, first of all when you're going to make a film you must Decide if its a thriller or a drama! As a drama the movie is watchable. Parents are divorcing & arguing like in real life. And then we have Jake with his closet which totally ruins all the film! I expected to see a BOOGEYMAN similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. As for the shots with Jake: just ignore them."

In [16]:
#converted all movies reviews to lower case
df['review'] = df['review'].str.lower()

In [17]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [18]:
import re  #regular expression

def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'', text)

In [19]:
df['review'] = df['review'].apply(remove_html_tags)

In [20]:
df.head(5)

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [21]:
def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'', text)

In [25]:
text1 = "Check out this website: https://www.example.com/data/snap for more information."

In [26]:
remove_url(text1)

'Check out this website:  for more information.'

In [27]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [28]:
exclude = string.punctuation

In [29]:
def remove_punc(text):
    for char in exclude:
        text = text.replace(char, '')
    return text

In [30]:
text2 = "Hello, world! This is a test sentence with punctuation."

In [31]:
remove_punc(text2)

'Hello world This is a test sentence with punctuation'

In [33]:
chat_words = {'u2':'you too', 'brb':'be right back', 'idk':"I don't know", 'smh':'shaking my head'}

In [36]:
def chat_convo(text):
    new_text = []
    for word in text.split():
        if word.lower() in chat_words:
            new_text.append(chat_words[word.lower()])
        else:
            new_text.append(word)
    return " ".join(new_text)

In [37]:
chat_convo("idk what to do, brb")

"I don't know what to do, be right back"

In [38]:
#Spelling correction

In [39]:
from textblob import TextBlob

In [46]:
incorrect_text = "I havee a speling misake in thise sentense."

textBlb = TextBlob(incorrect_text)
textBlb.correct().string

'I have a spelling mistake in this sentence.'

In [47]:
#Remove Stop Words

In [48]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

In [49]:
STOPWORDS = set(stopwords.words('english'))

In [50]:
#manually work
def remove_stopwords(text):
    new_text = []
    for word in text.split():
        if word not in STOPWORDS:
            new_text.append(word)
    x = new_text[:]
    new_text.clear()
    return " ".join(x)

remove_stopwords("This is a sample sentence and with some stop words.")

'This sample sentence stop words.'

# TOkenization

In [52]:
# approach tokenization using split function

#1. Word Tokenization

sent1 = "Hello, how are you doing today?"

sent1.split()

['Hello,', 'how', 'are', 'you', 'doing', 'today?']

In [60]:
#2. Sentence Tokenization

sent2 = "Hello, how are you doing today? I hope you are doing well. I am too."
sent2.split('.' )

['Hello, how are you doing today? I hope you are doing well', ' I am too', '']

In [76]:
from nltk.tokenize import word_tokenize, sent_tokenize

In [77]:
import nltk 
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [79]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

True

In [81]:
sent1 = "Hello, how are you doing today"

word_tokenize(sent1)

['Hello', ',', 'how', 'are', 'you', 'doing', 'today']

In [82]:
sent2 = "Hello, how are you doing today? I hope you are doing well. I am too."
word_tokenize(sent2)

['Hello',
 ',',
 'how',
 'are',
 'you',
 'doing',
 'today',
 '?',
 'I',
 'hope',
 'you',
 'are',
 'doing',
 'well',
 '.',
 'I',
 'am',
 'too',
 '.']

In [83]:
# Inflection : the process of changing the form of a word to express different grammatical features such as tense, case, voice, aspect, person

#Stemming : the process of reducing a word to its base or root form, which may not be a valid word in the language but serves as a common representation for related words. Stemming is often used in information retrieval and natural language processing tasks to group together different forms of a word.

In [84]:
from nltk.stem.porter import PorterStemmer

In [85]:
ps = PorterStemmer()

def stem_words(text):
    return " ".join([ps.stem(word) for word in text.split()])

In [86]:
sample = "running runner runs ran"

stem_words(sample)

'run runner run ran'

In [87]:
sample2 = "walk walks walked walking"
stem_words(sample2)

'walk walk walk walk'

In [88]:
# the issue of stemming is that it may produce non-words or words that are not valid in the language. For example, the stem of "running" is "run", which is a valid word, but the stem of "runner" is "runner", which is not a valid word. This can lead to confusion and errors in natural language processing tasks.

In [89]:
# Lemmatization : the process of reducing a word to its base or root form, which is a valid word in the language. 
# Lemmatization takes into account the context and meaning of the word, and it uses a dictionary or vocabulary to find the correct base form. 
# Lemmatization is often used in natural language processing tasks to improve the accuracy of text analysis and information retrieval.

In [91]:
from nltk.stem import WordNetLemmatizer
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...

True

In [92]:
wordnet_lemmatizer = WordNetLemmatizer()

In [97]:
sentence = "The striped bats are hanging on their feet for best runner. why are they doing this? I am not sure. I will have to ask them."
punctuation = string.punctuation

sentence_words = nltk.word_tokenize(sentence)

for word in sentence_words:
    if word in sentence_words:
        sentence_words.remove(word)


print("{0:20}{1:20}".format("Word", "Lemma"))

for word in sentence_words:
    print("{0:20}{1:20}".format(word, wordnet_lemmatizer.lemmatize(word)))

Word                Lemma
striped             striped
are                 are
on                  on
feet                foot
best                best
are                 are
doing               doing
?                   ?
am                  am
sure                sure
.                   .
I                   I
have                have
ask                 ask
.                   .

In [99]:
review = df['review'][1]

In [100]:
review

'a wonderful little production. the filming technique is very unassuming- very old-time-bbc fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. the actors are extremely well chosen- michael sheen not only "has got all the polari" but he has all the voices down pat too! you can truly see the seamless editing guided by the references to williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. a masterful production about one of the great master\'s of comedy and his life. the realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. it plays on our knowledge and our senses, particularly with the scenes concerning orton and halliwell and the sets (particularly of their flat with halliwell\'s murals decorating every surface) are terribly well done.'

In [101]:
word_tokenize(review)

['a',
 'wonderful',
 'little',
 'production',
 '.',
 'the',
 'filming',
 'technique',
 'is',
 'very',
 'unassuming-',
 'very',
 'old-time-bbc',
 'fashion',
 'and',
 'gives',
 'a',
 'comforting',
 ',',
 'and',
 'sometimes',
 'discomforting',
 ',',
 'sense',
 'of',
 'realism',
 'to',
 'the',
 'entire',
 'piece',
 '.',
 'the',
 'actors',
 'are',
 'extremely',
 'well',
 'chosen-',
 'michael',
 'sheen',
 'not',
 'only',
 '``',
 'has',
 'got',
 'all',
 'the',
 'polari',
 "''",
 'but',
 'he',
 'has',
 'all',
 'the',
 'voices',
 'down',
 'pat',
 'too',
 '!',
 'you',
 'can',
 'truly',
 'see',
 'the',
 'seamless',
 'editing',
 'guided',
 'by',
 'the',
 'references',
 'to',
 'williams',
 "'",
 'diary',
 'entries',
 ',',
 'not',
 'only',
 'is',
 'it',
 'well',
 'worth',
 'the',
 'watching',
 'but',
 'it',
 'is',
 'a',
 'terrificly',
 'written',
 'and',
 'performed',
 'piece',
 '.',
 'a',
 'masterful',
 'production',
 'about',
 'one',
 'of',
 'the',
 'great',
 'master',
 "'s",
 'of',
 'comedy',
 'and',
 'his',
 'life',
 '.',
 'the',
 'realism',
 'really',
 'comes',
 'home',
 'with',
 'the',
 'little',
 'things',
 ':',
 'the',
 'fantasy',
 'of',
 'the',
 'guard',
 'which',
 ',',
 'rather',
 'than',
 'use',
 'the',
 'traditional',
 "'dream",
 "'",
 'techniques',
 'remains',
 'solid',
 'then',
 'disappears',
 '.',
 'it',
 'plays',
 'on',
 'our',
 'knowledge',
 'and',
 'our',
 'senses',
 ',',
 'particularly',
 'with',
 'the',
 'scenes',
 'concerning',
 'orton',
 'and',
 'halliwell',
 'and',
 'the',
 'sets',
 '(',
 'particularly',
 'of',
 'their',
 'flat',
 'with',
 'halliwell',
 "'s",
 'murals',
 'decorating',
 'every',
 'surface',
 ')',
 'are',
 'terribly',
 'well',
 'done',
 '.']

In [106]:
punctuation = string.punctuation

sentence_words = nltk.word_tokenize(review)

for word in sentence_words:
    if word in sentence_words:
        sentence_words.remove(word)


print("{0:20}{1:20}".format("Word", "Lemma"))

for word in sentence_words:
    print("{0:20}{1:20}".format(word, wordnet_lemmatizer.lemmatize(word)))

Word                Lemma
wonderful           wonderful
production          production
technique           technique
very                very
very                very
fashion             fashion
gives               give
comforting          comforting
discomforting       discomforting
sense               sense
piece               piece
michael             michael
not                 not
``                  ``
got                 got
''                  ''
he                  he
all                 all
the                 the
voices              voice
pat                 pat
!                   !
can                 can
see                 see
the                 the
seamless            seamless
guided              guided
the                 the
to                  to
entries             entry
not                 not
is                  is
well                well
the                 the
but                 but
is                  is
terrificly          terrificly
piece               piece
a                   a
production          production
one                 one
the                 the
master              master
of                  of
life                life
the                 the
realism             realism
really              really
home                home
the                 the
things              thing
the                 the
of                  of
the                 the
guard               guard
,                   ,
than                than
the                 the
'dream              'dream
'                   '
techniques          technique
solid               solid
disappears          disappears
it                  it
on                  on
knowledge           knowledge
and                 and
our                 our
,                   ,
the                 the
scenes              scene
orton               orton
and                 and
halliwell           halliwell
and                 and
the                 the
(                   (
of                  of
flat                flat
with                with
halliwell           halliwell
murals              mural
every               every
)                   )
are                 are
terribly            terribly
well                well
done                done