# Introduction To Deep Learning

##### Ml models works on less complex data, but DL models works on complex datasets.
##### DL -> Artificial Neural Network System

## Workflow of DL:

    --> Data ingestion -> data cleaning and preprocessing -> model sequential architecture
    
        ->Model Sequential architecture:
            1. input layer(neurons, activation fns, input_dimensions)
            2. hidden layer(neurons, activation fns)
            3. output layer(neurons, activation fns based on target)

        -> model.compile(loss,optimizer,metrics)
        -> model training
        -> model prediction
        -> model performance evaluation

##### *Activation functions* are mathematical functions that is used for finding non-lineraity from the data.
    -> when data is numerical we will use :Relu,tanh
    -> when data is categorical we will use :sigmoid(2 sub-categories),softmax(for more than 2 sub-categories)

#### *Optimizers*  are used for minimizing the loss function(actual - predicted)
    1.SGD + Momentum -> stucks on local minima while oscillating around it
    2.SGD+Momentum+NAG -> overcomes the problem of local minima and oscillation by looking ahead of the current position
    3.AdaGrad -> provides the solution of automatic learning rate but cannot find proper solution.
    4.RMSProp -> Resolves the issue of automatic learning rate by adding an constant epsilon
    5.Adam (Momentum + RMSprop)-> Combines the advantages of both Momentum and RMSProp by using moving averages of the gradients and squared gradients to adapt the learning rate for each parameter.

In [3]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv("Day12 data\\Attrition.csv")

In [5]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [6]:
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score

In [7]:
x= df.drop(columns=["Attrition"],axis=1)
y = df["Attrition"]

In [8]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 34 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   BusinessTravel            1470 non-null   object
 2   DailyRate                 1470 non-null   int64
 3   Department                1470 non-null   object
 4   DistanceFromHome          1470 non-null   int64
 5   Education                 1470 non-null   int64
 6   EducationField            1470 non-null   object
 7   EmployeeCount             1470 non-null   int64
 8   EmployeeNumber            1470 non-null   int64
 9   EnvironmentSatisfaction   1470 non-null   int64
 10  Gender                    1470 non-null   object
 11  HourlyRate                1470 non-null   int64
 12  JobInvolvement            1470 non-null   int64
 13  JobLevel                  1470 non-null   int64
 14  JobRole                   1470 non-null   object
 15  JobSatisfaction           1470 non-null   int64
 16  MaritalStatus             1470 non-null   object
 17  MonthlyIncome             1470 non-null   int64
 18  MonthlyRate               1470 non-null   int64
 19  NumCompaniesWorked        1470 non-null   int64
 20  Over18                    1470 non-null   object
 21  OverTime                  1470 non-null   object
 22  PercentSalaryHike         1470 non-null   int64
 23  PerformanceRating         1470 non-null   int64
 24  RelationshipSatisfaction  1470 non-null   int64
 25  StandardHours             1470 non-null   int64
 26  StockOptionLevel          1470 non-null   int64
 27  TotalWorkingYears         1470 non-null   int64
 28  TrainingTimesLastYear     1470 non-null   int64
 29  WorkLifeBalance           1470 non-null   int64
 30  YearsAtCompany            1470 non-null   int64
 31  YearsInCurrentRole        1470 non-null   int64
 32  YearsSinceLastPromotion   1470 non-null   int64
 33  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(8)
memory usage: 390.6+ KB

In [9]:
categorical_features  = ['BusinessTravel', 'Department', 'EducationField','Gender','JobRole','MaritalStatus','Over18','OverTime']

In [10]:
x_encoded = pd.get_dummies(x, columns = categorical_features, 
                           drop_first=True)

In [11]:
x_encoded.head()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,OverTime_Yes
0,41,1102,1,2,1,1,2,94,3,2,...,False,False,False,False,False,True,False,False,True,True
1,49,279,8,1,1,2,3,61,2,2,...,False,False,False,False,True,False,False,True,False,False
2,37,1373,2,2,1,4,4,92,2,1,...,True,False,False,False,False,False,False,False,True,True
3,33,1392,3,4,1,5,4,56,3,1,...,False,False,False,False,True,False,False,True,False,True
4,27,591,2,1,1,7,1,40,3,1,...,True,False,False,False,False,False,False,True,False,False

In [12]:
x_encoded = x_encoded.astype(int)

In [13]:
lb = LabelEncoder()

In [15]:
y_encoded = lb.fit_transform(y)
y_encoded

array([1, 0, 1, ..., 0, 0, 0], shape=(1470,))

In [16]:
x_train, x_test, y_train, y_test = train_test_split(x_encoded, y_encoded, test_size=0.2, random_state=42)

In [18]:
sc = StandardScaler()

In [19]:
x_train_scaled = sc.fit_transform(x_train)
x_test_scaled = sc.transform(x_test)

In [20]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(units = 128 ,activation='relu' ,input_dim=x_train_scaled.shape[1]), #input layer
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(units=64 ,activation='relu'), #hidden layer
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(units = 1 ,activation='sigmoid') #output layer
    ])

c:\Users\ASUS\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [21]:
#Complie the model

In [22]:
loss_fn = tf.keras.losses.BinaryCrossentropy()
metrics = ['accuracy']

In [23]:
learning_rate = 0.001
momentum = 0.9
optimizer = tf.keras.optimizers.SGD(
    learning_rate=learning_rate, 
    momentum=momentum,
    nesterov=True
    )

In [24]:
model.compile(optimizer= optimizer, loss=loss_fn, metrics=metrics)

In [25]:
#Model training

In [26]:
model.fit(x_train_scaled, y_train, 
          epochs=50, 
          batch_size=8, 
          validation_split=0.1
          )

Epoch 1/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7628 - loss: 0.5315 - val_accuracy: 0.7966 - val_loss: 0.5066
Epoch 2/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8318 - loss: 0.4550 - val_accuracy: 0.7966 - val_loss: 0.4800
Epoch 3/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8384 - loss: 0.4318 - val_accuracy: 0.7966 - val_loss: 0.4723
Epoch 4/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8393 - loss: 0.4076 - val_accuracy: 0.7966 - val_loss: 0.4560
Epoch 5/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8422 - loss: 0.3941 - val_accuracy: 0.7966 - val_loss: 0.4417
Epoch 6/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8450 - loss: 0.3963 - val_accuracy: 0.8051 - val_loss: 0.4370
Epoch 7/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8488 - loss: 0.3683 - val_accuracy: 0.7881 - val_loss: 0.4293
Epoch 8/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8554 - loss: 0.3568 - val_accuracy: 0.7966 - val_loss: 0.4221
Epoch 9/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8658 - loss: 0.3566 - val_accuracy: 0.8051 - val_loss: 0.4173
Epoch 10/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8611 - loss: 0.3536 - val_accuracy: 0.8136 - val_loss: 0.4143
Epoch 11/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8790 - loss: 0.3396 - val_accuracy: 0.8220 - val_loss: 0.4058
Epoch 12/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8715 - loss: 0.3272 - val_accuracy: 0.8475 - val_loss: 0.4040
Epoch 13/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8724 - loss: 0.3340 - val_accuracy: 0.8305 - val_loss: 0.3999
Epoch 14/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8819 - loss: 0.3096 - val_accuracy: 0.8390 - val_loss: 0.3991
Epoch 15/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8922 - loss: 0.3067 - val_accuracy: 0.8305 - val_loss: 0.3969
Epoch 16/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8781 - loss: 0.3033 - val_accuracy: 0.8475 - val_loss: 0.3949
Epoch 17/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8913 - loss: 0.2821 - val_accuracy: 0.8559 - val_loss: 0.3962
Epoch 18/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8866 - loss: 0.2905 - val_accuracy: 0.8305 - val_loss: 0.3950
Epoch 19/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8885 - loss: 0.2903 - val_accuracy: 0.8475 - val_loss: 0.3998
Epoch 20/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8828 - loss: 0.2854 - val_accuracy: 0.8475 - val_loss: 0.3979
Epoch 21/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8922 - loss: 0.2767 - val_accuracy: 0.8390 - val_loss: 0.3936
Epoch 22/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8951 - loss: 0.2676 - val_accuracy: 0.8305 - val_loss: 0.3923
Epoch 23/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8800 - loss: 0.2828 - val_accuracy: 0.8305 - val_loss: 0.3918
Epoch 24/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8941 - loss: 0.2711 - val_accuracy: 0.8390 - val_loss: 0.3941
Epoch 25/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8932 - loss: 0.2767 - val_accuracy: 0.8390 - val_loss: 0.3980
Epoch 26/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8960 - loss: 0.2591 - val_accuracy: 0.8390 - val_loss: 0.3999
Epoch 27/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8998 - loss: 0.2566 - val_accuracy: 0.8475 - val_loss: 0.3936
Epoch 28/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9045 - loss: 0.2631 - val_accuracy: 0.8475 - val_loss: 0.3922
Epoch 29/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8960 - loss: 0.2544 - val_accuracy: 0.8475 - val_loss: 0.4011
Epoch 30/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8998 - loss: 0.2410 - val_accuracy: 0.8475 - val_loss: 0.3959
Epoch 31/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9064 - loss: 0.2531 - val_accuracy: 0.8390 - val_loss: 0.3968
Epoch 32/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9112 - loss: 0.2393 - val_accuracy: 0.8390 - val_loss: 0.4044
Epoch 33/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8970 - loss: 0.2543 - val_accuracy: 0.8390 - val_loss: 0.4047
Epoch 34/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9026 - loss: 0.2444 - val_accuracy: 0.8390 - val_loss: 0.4017
Epoch 35/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9149 - loss: 0.2225 - val_accuracy: 0.8390 - val_loss: 0.4057
Epoch 36/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9140 - loss: 0.2208 - val_accuracy: 0.8390 - val_loss: 0.4083
Epoch 37/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8979 - loss: 0.2516 - val_accuracy: 0.8390 - val_loss: 0.4072
Epoch 38/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9083 - loss: 0.2161 - val_accuracy: 0.8390 - val_loss: 0.4130
Epoch 39/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9045 - loss: 0.2220 - val_accuracy: 0.8390 - val_loss: 0.4138
Epoch 40/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9064 - loss: 0.2245 - val_accuracy: 0.8390 - val_loss: 0.4219
Epoch 41/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9140 - loss: 0.2128 - val_accuracy: 0.8390 - val_loss: 0.4190
Epoch 42/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9130 - loss: 0.2061 - val_accuracy: 0.8390 - val_loss: 0.4234
Epoch 43/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9197 - loss: 0.2016 - val_accuracy: 0.8305 - val_loss: 0.4261
Epoch 44/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9026 - loss: 0.2196 - val_accuracy: 0.8390 - val_loss: 0.4331
Epoch 45/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9225 - loss: 0.1946 - val_accuracy: 0.8305 - val_loss: 0.4260
Epoch 46/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9206 - loss: 0.2074 - val_accuracy: 0.8390 - val_loss: 0.4302
Epoch 47/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9178 - loss: 0.1930 - val_accuracy: 0.8305 - val_loss: 0.4360
Epoch 48/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9244 - loss: 0.1834 - val_accuracy: 0.8475 - val_loss: 0.4484
Epoch 49/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9253 - loss: 0.2007 - val_accuracy: 0.8390 - val_loss: 0.4511
Epoch 50/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9055 - loss: 0.2002 - val_accuracy: 0.8390 - val_loss: 0.4466

In [28]:
loss , accuracy = model.evaluate(x_test_scaled, y_test)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8639 - loss: 0.3689