In [ ]:
import numpy as np
import pandas as pd

In [2]:
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score

In [3]:
df = pd.read_csv('Day 10 Practise 2nd\\covid_toy.csv')

In [4]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [5]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [6]:
df['fever'] = df['fever'].fillna(df['fever'].mean())

In [7]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [8]:
lb = LabelEncoder()

In [14]:
df['gender'] = lb.fit_transform(df['gender'])
df['cough'] = lb.fit_transform(df['cough'])
df['city'] = lb.fit_transform(df['city'])
df['has_covid'] = lb.fit_transform(df['has_covid'])

In [15]:
df.head()

   age  gender  fever  cough  city  has_covid
0   60       1  103.0      0     2          0
1   27       1  100.0      0     1          1
2   42       1  101.0      0     1          0
3   31       0   98.0      0     2          0
4   65       0  101.0      0     3          0

In [16]:
x = df.drop(columns=['has_covid'], axis=1)
y= df['has_covid']

In [34]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [35]:
sc= StandardScaler()

In [36]:
x_train_scaled =sc.fit_transform(x_train)
x_test_scaled = sc.fit_transform(x_test)

In [37]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(units = 128 ,activation='relu' ,input_dim=x_train_scaled.shape[1]), #input layer
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(units=64 ,activation='relu'), #hidden layer
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(units = 1 ,activation='sigmoid') #output layer
    ])

c:\Users\ASUS\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [38]:
loss_fn = tf.keras.losses.BinaryCrossentropy()
metrics = ['accuracy']

In [39]:
learning_rate = 0.001
momentum = 0.9
optimizer = tf.keras.optimizers.SGD(
    learning_rate=learning_rate, 
    momentum=momentum,
    nesterov=True
    )

In [40]:
model.compile(optimizer= optimizer, loss=loss_fn, metrics=metrics)

In [41]:
model.fit(x_train_scaled, y_train, 
          epochs=50, 
          batch_size=8, 
          validation_split=0.1
          )

Epoch 1/50

9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.5000 - loss: 0.7207 - val_accuracy: 0.7500 - val_loss: 0.6601
Epoch 2/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5139 - loss: 0.6993 - val_accuracy: 0.7500 - val_loss: 0.6594
Epoch 3/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6111 - loss: 0.6923 - val_accuracy: 0.8750 - val_loss: 0.6595
Epoch 4/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5417 - loss: 0.6919 - val_accuracy: 0.7500 - val_loss: 0.6590
Epoch 5/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4583 - loss: 0.7019 - val_accuracy: 0.7500 - val_loss: 0.6582
Epoch 6/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5000 - loss: 0.7062 - val_accuracy: 0.7500 - val_loss: 0.6580
Epoch 7/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4861 - loss: 0.7148 - val_accuracy: 0.7500 - val_loss: 0.6575
Epoch 8/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5139 - loss: 0.6996 - val_accuracy: 0.7500 - val_loss: 0.6579
Epoch 9/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6528 - loss: 0.6666 - val_accuracy: 0.7500 - val_loss: 0.6572
Epoch 10/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5139 - loss: 0.7013 - val_accuracy: 0.7500 - val_loss: 0.6575
Epoch 11/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5833 - loss: 0.6798 - val_accuracy: 0.6250 - val_loss: 0.6572
Epoch 12/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5000 - loss: 0.6868 - val_accuracy: 0.6250 - val_loss: 0.6574
Epoch 13/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6250 - loss: 0.6773 - val_accuracy: 0.5000 - val_loss: 0.6581
Epoch 14/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5556 - loss: 0.6701 - val_accuracy: 0.5000 - val_loss: 0.6585
Epoch 15/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5694 - loss: 0.6875 - val_accuracy: 0.5000 - val_loss: 0.6585
Epoch 16/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5556 - loss: 0.6880 - val_accuracy: 0.5000 - val_loss: 0.6583
Epoch 17/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6528 - loss: 0.6719 - val_accuracy: 0.5000 - val_loss: 0.6583
Epoch 18/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.4722 - loss: 0.7148 - val_accuracy: 0.5000 - val_loss: 0.6588
Epoch 19/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5556 - loss: 0.6788 - val_accuracy: 0.5000 - val_loss: 0.6596
Epoch 20/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7222 - loss: 0.6569 - val_accuracy: 0.5000 - val_loss: 0.6590
Epoch 21/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5556 - loss: 0.6830 - val_accuracy: 0.5000 - val_loss: 0.6591
Epoch 22/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6389 - loss: 0.6613 - val_accuracy: 0.5000 - val_loss: 0.6585
Epoch 23/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5556 - loss: 0.6895 - val_accuracy: 0.5000 - val_loss: 0.6582
Epoch 24/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5694 - loss: 0.6929 - val_accuracy: 0.5000 - val_loss: 0.6587
Epoch 25/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5000 - loss: 0.7001 - val_accuracy: 0.5000 - val_loss: 0.6588
Epoch 26/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5833 - loss: 0.6975 - val_accuracy: 0.5000 - val_loss: 0.6593
Epoch 27/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6389 - loss: 0.6751 - val_accuracy: 0.5000 - val_loss: 0.6599
Epoch 28/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5556 - loss: 0.6849 - val_accuracy: 0.5000 - val_loss: 0.6612
Epoch 29/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6528 - loss: 0.6631 - val_accuracy: 0.5000 - val_loss: 0.6617
Epoch 30/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6806 - loss: 0.6675 - val_accuracy: 0.5000 - val_loss: 0.6618
Epoch 31/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5556 - loss: 0.6875 - val_accuracy: 0.6250 - val_loss: 0.6617
Epoch 32/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5833 - loss: 0.6695 - val_accuracy: 0.6250 - val_loss: 0.6613
Epoch 33/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6250 - loss: 0.6626 - val_accuracy: 0.6250 - val_loss: 0.6618
Epoch 34/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6667 - loss: 0.6624 - val_accuracy: 0.6250 - val_loss: 0.6618
Epoch 35/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5417 - loss: 0.6933 - val_accuracy: 0.6250 - val_loss: 0.6628
Epoch 36/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5556 - loss: 0.6704 - val_accuracy: 0.6250 - val_loss: 0.6639
Epoch 37/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5833 - loss: 0.6816 - val_accuracy: 0.6250 - val_loss: 0.6654
Epoch 38/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5556 - loss: 0.6855 - val_accuracy: 0.6250 - val_loss: 0.6656
Epoch 39/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5556 - loss: 0.6571 - val_accuracy: 0.6250 - val_loss: 0.6653
Epoch 40/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6944 - loss: 0.6425 - val_accuracy: 0.6250 - val_loss: 0.6671
Epoch 41/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6111 - loss: 0.6583 - val_accuracy: 0.6250 - val_loss: 0.6682
Epoch 42/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5833 - loss: 0.6875 - val_accuracy: 0.6250 - val_loss: 0.6682
Epoch 43/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5417 - loss: 0.6901 - val_accuracy: 0.6250 - val_loss: 0.6691
Epoch 44/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5972 - loss: 0.6782 - val_accuracy: 0.6250 - val_loss: 0.6698
Epoch 45/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5556 - loss: 0.6719 - val_accuracy: 0.6250 - val_loss: 0.6706
Epoch 46/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6111 - loss: 0.6762 - val_accuracy: 0.6250 - val_loss: 0.6706
Epoch 47/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5694 - loss: 0.6672 - val_accuracy: 0.6250 - val_loss: 0.6709
Epoch 48/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6389 - loss: 0.6593 - val_accuracy: 0.6250 - val_loss: 0.6722
Epoch 49/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6528 - loss: 0.6521 - val_accuracy: 0.6250 - val_loss: 0.6733
Epoch 50/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6389 - loss: 0.6701 - val_accuracy: 0.6250 - val_loss: 0.6743

In [42]:
loss , accuracy = model.evaluate(x_test_scaled, y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - accuracy: 0.6500 - loss: 0.6399