# DAY 2 - PANDAS

Pandas is used to handle data manipulations.

In [1]:
import pandas as pd

1. Series -> one dimensional array, it shows only values, not column names.

In [3]:
a=pd.Series([1,2,3,4,5])
print(type(a))
a

<class 'pandas.core.series.Series'>

0    1
1    2
2    3
3    4
4    5
dtype: int64

2. DataFrame -> multidimensional array and it shows col name with thier values.

In [52]:
a ={
    "Id": [1,2,3,4,5],
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Dept": ["Sales", "IT", "IT", "IT", "Sales"],
    "Salary": [25000, 30000, 35000, 40000, 45000],
    "Working Hours": [8, 9, 7, 8, 6], 
} #dictionary of lists

df= pd.DataFrame(a)
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>

   Id     Name   Dept  Salary  Working Hours
0   1    Alice  Sales   25000              8
1   2      Bob     IT   30000              9
2   3  Charlie     IT   35000              7
3   4    David     IT   40000              8
4   5      Eve  Sales   45000              6

Export or import a file

In [8]:
##exporting to csv
#with index
df.to_csv("emp.csv")
#without index
df.to_csv("emp2.csv", index=False)

In [ ]:
#importing from csv
#give absolute path if the file is not in the same directory
df1=pd.read_csv("emp2.csv")
df1

   Id     Name       Dept  Salary  Working Hours
0   1    Alice         HR   25000              8
1   2      Bob         IT   30000              9
2   3  Charlie    Finance   35000              7
3   4    David  Marketing   40000              8
4   5      Eve      Sales   45000              6

Web scraping:
with the help of extension, we created csv file from live searches. and now we will read the data from that file.

In [22]:
hotels = pd.read_csv("mussorrie hotels.csv")
hotels

,BgYkof,lXJaOd,UqrZme,LtjZ2d,LtjZ2d 2,LtjZ2d 3,LtjZ2d 4,LtjZ2d 5,LtjZ2d 6,LtjZ2d 7,M9PkR src,LtjZ2d 8,Unnamed: 12,Unnamed: 13
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Club Mahindra Resort - Mussoorie, Uttarakhand",Location · Service · Property,Amenities for Club Mahindra Resort - Mussoorie...,4-star hotel,Breakfast,Free Wi-Fi,Air conditioning,Restaurant,Kitchen in some rooms,Full-service laundry,Child-friendly,NaN,NaN,NaN
3,Zostel Mussoorie (Mall Road),Nightlife · Service · Property,Amenities for Zostel Mussoorie (Mall Road): Fr...,NaN,Free Wi-Fi,Parking ($),Breakfast,Restaurant,Kitchen in some rooms,Full-service laundry,NaN,"₹1,624",NaN,NaN
4,Mango Tree Courtyard Mussoorie,Service · Location · Breakfast,Amenities for Mango Tree Courtyard Mussoorie: ...,NaN,Free breakfast,Free Wi-Fi,Free parking,Pet-friendly,Restaurant,Room service,Kitchen in some rooms,"₹4,315",Full-service laundry,Child-friendly
5,Set your dates to update prices,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,"The Hosteller Mussoorie, Mall Road",Service · Location · Property,"Amenities for The Hosteller Mussoorie, Mall Ro...",3-star hotel,Breakfast ($),Free Wi-Fi,Pet-friendly,Parking,Restaurant,Airport shuttle,NaN,NaN,NaN,NaN
7,Hotel Skylark by Gabrian Hotels,Service · Property · Location,"Amenities for Hotel Skylark by Gabrian Hotels,...",3-star hotel,Breakfast ($),Free Wi-Fi,Free parking,Restaurant,Room service,Full-service laundry,Accessible,NaN,Child-friendly,NaN
8,Hotel Highland by DLS Hotels,Service · Dining · Property,"Amenities for Hotel Highland by DLS Hotels, a ...",4-star hotel,Free breakfast,Free Wi-Fi,Parking,Restaurant,Room service,Kitchen in rooms,Airport shuttle,"₹6,615",Full-service laundry,NaN
9,"Shiva Continental, Mussoorie",Service · Location · Breakfast,"Amenities for Shiva Continental, Mussoorie, a ...",3-star hotel,Breakfast ($),Free Wi-Fi,Free parking,Restaurant,Room service,Kitchen in some rooms,Full-service laundry,"₹4,355",NaN,NaN
10,Renest Dunsvirk Court Mussoorie,Service · Location · Property,"Amenities for Renest Dunsvirk Court Mussoorie,...",4-star hotel,Free breakfast,Free Wi-Fi,Parking,Air conditioning,Fitness centre,Spa,Bar,"₹8,856",Restaurant,NaN
11,"Hotel Green Castle, Mall road, Mussoorie",Service · Location · Property,"Amenities for Hotel Green Castle, Mall road, M...",4-star hotel,Free breakfast,Free Wi-Fi,Free parking,Spa,Restaurant,Room service,Full-service laundry,"₹7,313",Accessible,NaN
12,"Welcomhotel By ITC Hotels, The Savoy, Mussoorie",Property · Service · Dining,"Amenities for Welcomhotel By ITC Hotels, The S...",5-star hotel,Free breakfast,Wi-Fi,Free parking,Pool,Air conditioning,Fitness centre,Spa,"₹41,300",Bar,NaN
13,Hotel Crystal Palace Mussoorie,Service · Dining · Property,"Amenities for Hotel Crystal Palace Mussoorie, ...",3-star hotel,Breakfast ($),Free Wi-Fi,Free parking,Hot tub,Air conditioning,Pet-friendly,Fitness centre,"₹3,616",Restaurant,NaN
14,Hotel Wild Wood by Ginseng Hotels,Service · Location · Property,Amenities for Hotel Wild Wood by Ginseng Hotel...,NaN,Breakfast ($),Free Wi-Fi,Free parking,Restaurant,Room service,Airport shuttle,Full-service laundry,NaN,Business centre,NaN
15,Echor Baris Resort Mussoorie,Service · Property · Dining,Amenities for Echor Baris Resort Mussoorie: Br...,NaN,Breakfast ($),Free Wi-Fi,Free parking,Air conditioning,Restaurant,Room service,Airport shuttle,NaN,Full-service laundry,Accessible
16,"Tree of Life Highlands, Mussoorie",Pets · Service · Dining,"Amenities for Tree of Life Highlands, Mussoori...",4-star hotel,Free breakfast,Free Wi-Fi,Free parking,Pet-friendly,Restaurant,Room service,Kitchen in some rooms,"₹9,251",Airport shuttle,NaN
17,Ramada By Wyndham Mussoorie Mall Road,Service · Dining · Property,Amenities for Ramada By Wyndham Mussoorie Mall...,4-star hotel,Free breakfast,Free Wi-Fi,Free parking,Pool,Air conditioning,Fitness centre,Spa,NaN,Bar,NaN
18,HOTEL SAMRAT - ON MALL ROAD,Room · Location · Property,Amenities for HOTEL SAMRAT - ON MALL ROAD: Bre...,NaN,Breakfast,Free Wi-Fi,Parking,Air conditioning,Pet-friendly,Restaurant,Room service,"₹1,049",Kitchen in some rooms,Full-service laundry
19,CEYONE - Classic Fall Resort,Service · Dining · Property,"Amenities for CEYONE - Classic Fall Resort, a ...",3-star hotel,Breakfast ($),Free Wi-Fi,Free parking,Outdoor pool,Restaurant,Room service,Airport shuttle,NaN,Full-service laundry,NaN
20,goSTOPS Mussoorie Picture Palace,Bathroom · Sleep,Amenities for goSTOPS Mussoorie Picture Palace...,NaN,Breakfast ($),Free Wi-Fi,Free parking,Air conditioning,Pet-friendly,Restaurant,Kitchen in some rooms,NaN,Airport shuttle,Full-service laundry
21,Majestic Himalayan View Rooms in delightful Mu...,NaN,Amenities for Majestic Himalayan View Rooms in...,NaN,House,Sleeps 2,1 bedroom,1 bathroom,1 bed,Ironing board,Kitchen,"₹5,098",No parking,No Wi-Fi
22,Jungle Jostel Homestay,NaN,"Amenities for Jungle Jostel Homestay: House, S...",NaN,House,Sleeps 4,2 bedrooms,2 bathrooms,2 beds,Child-friendly,Ironing board,"₹1,997",Smoke-free,No airport shuttle

In [23]:
Phones = pd.read_csv("flipkart.csv")
Phones

,NAME,RATINGS,TOTAL RATINGS,STORAGE,CAMERA,BATTERY,PROCESSOR,WARRANTY,PRICE,OFFER
0,OPPO K13 5G with 7000mAh and 80W SUPERVOOC Cha...,4.4,"73,745 Ratings",8 GB RAM | 256 GB ROM,50MP + 2MP | 16MP Front Camera,7000 mAh Battery,Snapdragon 6 Gen 4 Processor,80W SUPERVOOC Charger,"₹24,999",NaN
1,Samsung Galaxy S24 5G Snapdragon (Cobalt Viole...,4.6,"57,437 Ratings",8 GB RAM | 256 GB ROM,50MP + 12MP | 12MP Front Camera,4000 mAh Battery,8 Gen 3 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹55,999",30% off
2,"Apple iPhone 17 (Black, 256 GB)",4.6,"12,927 Ratings",256 GB ROM,48MP + 48MP | 18MP Front Camera,"A19 Chip, 6 Core Processor Processor",Apple One (1) Year Limited Warranty,NaN,"₹82,900",NaN
3,"Samsung Galaxy S26 5G (Sky Blue, 256 GB)",4.7,375 Ratings,12 GB RAM | 256 GB ROM,50MP + 12MP | 12MP Front Camera,4300 mAh Li-ion Battery,2600 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹87,999",NaN
4,"OPPO Reno15 5G (Twilight Blue, 256 GB)",4.5,681 Ratings,8 GB RAM | 256 GB ROM,50MP + 50MP + 8MP | Yes,6500 mAh Battery,7 Gen 4 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹47,999",4% off
5,"Samsung Galaxy S25 FE 5G (Jetblack, 256 GB)",4.6,"1,280 Ratings",8 GB RAM | 256 GB ROM,50MP + 12MP + 8MP | 12MP Front Camera,4900 mAh Li-ion Battery,Exynos 2400 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹65,999",NaN
6,"Samsung Galaxy S24 5G Snapdragon (Onyx Black, ...",4.6,"57,437 Ratings",8 GB RAM | 128 GB ROM,50MP + 12MP | 12MP Front Camera,4000 mAh Battery,8 Gen 3 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹49,999",33% off
7,"Samsung Galaxy S25 FE 5G (Navy, 256 GB)",4.6,"1,280 Ratings",8 GB RAM | 256 GB ROM,50MP + 12MP + 8MP | 12MP Front Camera,4900 mAh Li-ion Battery,Exynos 2400 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹65,999",NaN
8,"Samsung Galaxy S26 5G (Black, 256 GB)",4.7,375 Ratings,12 GB RAM | 256 GB ROM,50MP + 12MP | 12MP Front Camera,4300 mAh Li-ion Battery,2600 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹87,999",NaN
9,"Apple iPhone 15 (Black, 128 GB)",4.6,"2,45,694 Ratings",128 GB ROM,48MP + 12MP | 12MP Front Camera,"A16 Bionic Chip, 6 Core Processor Processor",1 year warranty for phone and 1 year warranty ...,NaN,"₹59,900",NaN
10,"Samsung Galaxy S24 5G Snapdragon (Onyx Black, ...",4.6,"57,437 Ratings",8 GB RAM | 256 GB ROM,50MP + 12MP | 12MP Front Camera,4000 mAh Battery,8 Gen 3 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹55,999",30% off
11,"OnePlus 12 (Glacial White, 256 GB)",4.6,"1,595 Ratings",12 GB RAM | 256 GB ROM,50MP Rear Camera,5400 mAh Battery,Qualcomm SM8650-AB Snapdragon 8 Gen 3 (4 nm) P...,1 Year manufacturer warranty for device and 1 ...,"₹49,180",24% off
12,"Samsung Galaxy S25 5G (Silver Shadow, 128 GB)",4.6,"3,544 Ratings",12 GB RAM | 128 GB ROM,50MP + 10MP + 12MP | 12MP Front Camera,4000 mAh Battery,8 Elite for Galaxy Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹56,999",24% off
13,"Samsung Galaxy S25 Edge 5G (Titanium Jetblack,...",4.4,127 Ratings,12 GB RAM | 256 GB ROM,200MP + 12MP | 12MP Front Camera,3900 mAh Battery,Qualcomm Snapdragon 8 Elite for Galaxy Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹69,999",36% off
14,"Nothing Phone (3) (Black, 512 GB)",4.4,719 Ratings,16 GB RAM | 512 GB ROM,50MP + 50MP + 50MP | 50MP Front Camera,5500 mAh Battery,8s Gen 4 Mobile Platform Processor,1 Year Manufacturing Warranty,"₹89,999",5% off
15,"OPPO Reno15 5G (Twilight Blue, 256 GB)",4.5,364 Ratings,12 GB RAM | 256 GB ROM,50MP + 50MP + 8MP | Yes,6500 mAh Battery,7 Gen 4 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹50,999",7% off
16,"MOTOROLA Signature (PANTONE Carbon, 1 TB)",4.5,572 Ratings,16 GB RAM | 1 TB ROM,50MP + 50MP + 50MP | 50MP Front Camera,5200 mAh Battery,Snapdragon 8 Gen 5 Processor,1 Year Warranty on Handset and 6 Months Warran...,"₹67,499",20% off
17,"MOTOROLA Signature (PANTONE Carbon, 512 GB)",4.5,572 Ratings,16 GB RAM | 512 GB ROM,50MP + 50MP + 50MP | 50MP Front Camera,5200 mAh Battery,Snapdragon 8 Gen 5 Processor,1 Year Warranty on Handset and 6 Months Warran...,"₹62,499",21% off
18,"Samsung Galaxy S25 FE 5G (White, 256 GB)",4.6,"1,280 Ratings",8 GB RAM | 256 GB ROM,50MP + 12MP + 8MP | 12MP Front Camera,4900 mAh Li-ion Battery,Exynos 2400 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹65,999",NaN
19,"Samsung Galaxy S26 5G (Cobalt Violet, 256 GB)",4.7,375 Ratings,12 GB RAM | 256 GB ROM,50MP + 12MP | 12MP Front Camera,4300 mAh Li-ion Battery,2600 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹87,999",NaN
20,"vivo V70 Elite (Authentic Black, 256 GB)",4.6,675 Ratings,8 GB RAM | 256 GB ROM,50MP + 50MP + 8MP | Yes,6500 mAh Li-ion battery Battery,Snapdragon 8s Gen 3 Processor,1 Year Warranty on Handset and 6 Months Warran...,"₹54,999",NaN
21,"OnePlus Nord 6 (Pitch Black, 256 GB)",4.7,56 Ratings,12 GB RAM | 256 GB ROM | Expandable Upto 256 GB,50MP Rear Camera,9000 mAh Battery,4 octa-core processor Processor,one-year limited warranty starting from the da...,"₹51,298",10% off
22,"Apple iPhone 17 (White, 256 GB)",4.6,"12,927 Ratings",256 GB ROM,48MP + 48MP | 18MP Front Camera,"A19 Chip, 6 Core Processor Processor",Apple One (1) Year Limited Warranty,NaN,"₹82,900",NaN
23,"Google Pixel 9A (Obsidian, 256 GB)",4.4,"10,598 Ratings",8 GB RAM | 256 GB ROM,48MP + 12MP | 12MP Front Camera,5100 mAh Battery,Tensor G4 Processor,1 Year Domestic Warranty,"₹39,999",20% off

In [24]:
df

   Id     Name       Dept  Salary  Working Hours
0   1    Alice         HR   25000              8
1   2      Bob         IT   30000              9
2   3  Charlie    Finance   35000              7
3   4    David  Marketing   40000              8
4   5      Eve      Sales   45000              6

In [25]:
df.head(2) #first 2 rows

   Id   Name Dept  Salary  Working Hours
0   1  Alice   HR   25000              8
1   2    Bob   IT   30000              9

In [26]:
df.tail(2) #last 2 rows

   Id   Name       Dept  Salary  Working Hours
3   4  David  Marketing   40000              8
4   5    Eve      Sales   45000              6

In [ ]:
#statistical summary of the data
df.describe()

             Id       Salary  Working Hours
count  5.000000      5.00000       5.000000
mean   3.000000  35000.00000       7.600000
std    1.581139   7905.69415       1.140175
min    1.000000  25000.00000       6.000000
25%    2.000000  30000.00000       7.000000
50%    3.000000  35000.00000       8.000000
75%    4.000000  40000.00000       8.000000
max    5.000000  45000.00000       9.000000

In [29]:
#df.info() #gives info about the data like number of non null values, datatype of each column, memory usage etc.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             5 non-null      int64
 1   Name           5 non-null      object
 2   Dept           5 non-null      object
 3   Salary         5 non-null      int64
 4   Working Hours  5 non-null      int64
dtypes: int64(3), object(2)
memory usage: 332.0+ bytes

In [32]:
df.sample() #randomly samples one row from the dataframe

   Id Name   Dept  Salary  Working Hours
4   5  Eve  Sales   45000              6

In [35]:
df.shape #gives number of rows and columns in the dataframe

(5, 5)

In [36]:
df.columns #gives the column names of the dataframe

Index(['Id', 'Name', 'Dept', 'Salary', 'Working Hours'], dtype='object')

In [54]:
df['Dept']

0    1
1    0
2    0
3    0
4    1
Name: Dept, dtype: int64

In [53]:
df['Dept'] = df['Dept'].map({"Sales": 1, "IT": 0})
df

   Id     Name  Dept  Salary  Working Hours
0   1    Alice     1   25000              8
1   2      Bob     0   30000              9
2   3  Charlie     0   35000              7
3   4    David     0   40000              8
4   5      Eve     1   45000              6

LOC AND ILOC

In [ ]:
#df.loc[row_range,column_name]
#last index of row is inclusive in loc
df.loc[1:4,['Name','Salary']]

      Name  Salary
1      Bob   30000
2  Charlie   35000
3    David   40000
4      Eve   45000

In [ ]:
#df.iloc[row_range,column_range]
#last index of row and column is exclusive in iloc
df.iloc[1:4,[2,3,4]]

   Dept  Salary  Working Hours
1     0   30000              9
2     0   35000              7
3     0   40000              8

In [57]:
df.iloc[1:4,2:5]

   Dept  Salary  Working Hours
1     0   30000              9
2     0   35000              7
3     0   40000              8

In [59]:
df[df['Working Hours']>=8]

   Id   Name  Dept  Salary  Working Hours
0   1  Alice     1   25000              8
1   2    Bob     0   30000              9
3   4  David     0   40000              8

In [60]:
df[df['Dept']==0]

   Id     Name  Dept  Salary  Working Hours
1   2      Bob     0   30000              9
2   3  Charlie     0   35000              7
3   4    David     0   40000              8

In [61]:
df[df['Salary']>30000]

   Id     Name  Dept  Salary  Working Hours
2   3  Charlie     0   35000              7
3   4    David     0   40000              8
4   5      Eve     1   45000              6

In [62]:
df.dtypes #gives the datatype of each column in the dataframe

Id                int64
Name             object
Dept              int64
Salary            int64
Working Hours     int64
dtype: object

In [65]:
df['Working Hours'] = df['Working Hours'].astype(float) #converting the datatype of a column to float
df['Salary'] = df['Salary'].astype(float)
df.dtypes

Id                 int64
Name              object
Dept               int64
Salary           float64
Working Hours    float64
dtype: object