# DAY 5

Workflow in ML Models

### Data Dividation
    df : x(input),y(target)
    x : x_train,x_test
    y : y_train,y_test
    ML MODEL (x_train,y_train)->model(x_test)->o/p ??y_pred
    compare : y_test and y_pred

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('covid_toy.csv')

In [4]:
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [5]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [6]:
df["fever"] = df['fever'].fillna(df['fever'].mean())

In [7]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [8]:
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [10]:
df.shape

(100, 6)

In [11]:
x = df.drop(columns = ["has_covid"]) ##input data
y = df['has_covid'] ##output data

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2,random_state = 42)

In [14]:
print("Total Data Shape: ", df.shape)
print("----------------------------")
print("Input Data Shape: ", x.shape)
print("x_train Data Shape: ", x_train.shape)
print("x_test Data Shape: ", x_test.shape)
print("----------------------------")
print("Output Data Shape: ", y.shape)
print("y_train Data Shape: ", y_train.shape)
print("y_test Data Shape: ", y_test.shape)

Total Data Shape:  (100, 6)
----------------------------
Input Data Shape:  (100, 5)
x_train Data Shape:  (80, 5)
x_test Data Shape:  (20, 5)
----------------------------
Output Data Shape:  (100,)
y_train Data Shape:  (80,)
y_test Data Shape:  (20,)

### Normal Distribution convert -> calculations easy ,less model training time

    Normal Distribution Condition -> mean=0, std_deviation(next value)=1

### ENCODING -> Transforming categorical data into numerical data

In [28]:
df.describe()

              age      gender       fever       cough        city  has_covid
count  100.000000  100.000000  100.000000  100.000000  100.000000     100.00
mean    44.220000    0.410000  100.844444    0.380000    1.340000       0.45
std     24.878931    0.494311    1.948380    0.487832    1.075156       0.50
min      5.000000    0.000000   98.000000    0.000000    0.000000       0.00
25%     20.000000    0.000000   99.000000    0.000000    0.000000       0.00
50%     45.000000    0.000000  100.922222    0.000000    1.000000       0.00
75%     66.500000    1.000000  102.000000    1.000000    2.000000       1.00
max     84.000000    1.000000  104.000000    1.000000    3.000000       1.00

In [21]:
from sklearn.preprocessing import LabelEncoder

In [22]:
lb = LabelEncoder()

In [24]:
df['gender'] = lb.fit_transform(df['gender'])
df['cough'] = lb.fit_transform(df['cough'])
df['city'] = lb.fit_transform(df['city'])
df['has_covid'] = lb.fit_transform(df['has_covid'])

In [30]:
df.head()

   age  gender  fever  cough  city  has_covid
0   60       1  103.0      0     2          0
1   27       1  100.0      0     1          1
2   42       1  101.0      0     1          0
3   31       0   98.0      0     2          0
4   65       0  101.0      0     3          0

In [31]:
x= df.drop(columns = ["has_covid"]) ##input data
y = df['has_covid'] ##output data

In [32]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2,random_state = 42)

In [33]:
np.round(x_train.describe(),2 )

         age  gender   fever  cough   city
count  80.00   80.00   80.00  80.00  80.00
mean   42.91    0.41  100.98   0.40   1.30
std    24.47    0.50    1.93   0.49   1.12
min     5.00    0.00   98.00   0.00   0.00
25%    20.00    0.00  100.00   0.00   0.00
50%    42.00    0.00  101.00   0.00   1.00
75%    65.00    1.00  102.00   1.00   2.00
max    84.00    1.00  104.00   1.00   3.00

In [34]:
# for converting our data into normal distribution we will use standard scaler

In [36]:
from sklearn.preprocessing import StandardScaler

In [37]:
sc = StandardScaler()

In [38]:
x_train_sc =sc.fit_transform(x_train)

In [39]:
x_train_new = pd.DataFrame(x_train_sc,columns=x_train.columns)

In [40]:
np.round(x_train_new.describe(),2   )

         age  gender  fever  cough   city
count  80.00   80.00  80.00  80.00  80.00
mean   -0.00    0.00  -0.00  -0.00  -0.00
std     1.01    1.01   1.01   1.01   1.01
min    -1.56   -0.84  -1.56  -0.82  -1.17
25%    -0.94   -0.84  -0.51  -0.82  -1.17
50%    -0.04   -0.84   0.01  -0.82  -0.27
75%     0.91    1.19   0.53   1.22   0.63
max     1.69    1.19   1.57   1.22   1.53

# 2ND DATASET

In [41]:
df1 = pd.read_csv('Churn_Modelling.csv')

In [43]:
df1.head(2)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0

Encoding

In [46]:
lb = LabelEncoder()

In [47]:
df1['Geography'] = lb.fit_transform(df1['Geography'])
df1['Surname'] = lb.fit_transform(df1['Surname'])
df1['Gender'] = lb.fit_transform(df1['Gender'])

Target defining and data splitting

In [48]:
x = df1.drop(columns = ["Exited"]) ##input data
y = df1['Exited'] ##output data

In [49]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2,random_state = 42)

In [50]:
np.round(x_train.describe(),2 )

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
count,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00
mean,5012.51,15690665.10,1502.17,651.65,0.75,0.55,38.90,5.00,76102.14,1.53,0.70,0.51,100431.29
std,2887.65,71847.43,847.15,96.37,0.83,0.50,10.52,2.88,62461.01,0.58,0.46,0.50,57518.92
min,2.00,15565701.00,0.00,350.00,0.00,0.00,18.00,0.00,0.00,1.00,0.00,0.00,90.07
25%,2512.75,15628215.50,765.00,585.00,0.00,0.00,32.00,3.00,0.00,1.00,0.00,0.00,51364.12
50%,5014.50,15690738.00,1525.00,653.00,1.00,1.00,37.00,5.00,96447.52,1.00,1.00,1.00,100487.72
75%,7505.25,15753164.25,2236.00,719.00,1.00,1.00,44.00,7.00,127611.33,2.00,1.00,1.00,149595.84
max,10000.00,15815660.00,2930.00,850.00,2.00,1.00,92.00,10.00,250898.09,4.00,1.00,1.00,199970.74

Normal Distribution

In [51]:
from sklearn.preprocessing import StandardScaler

In [52]:
sc = StandardScaler()

In [53]:
x_train_sc =sc.fit_transform(x_train)

In [54]:
x_train_new = pd.DataFrame(x_train_sc,columns=x_train.columns)

In [56]:
np.round(x_train_new.describe(),2)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
count,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00
mean,-0.00,0.00,-0.00,0.00,-0.00,0.00,-0.00,0.00,-0.00,0.00,-0.00,-0.00,0.00
std,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
min,-1.74,-1.74,-1.77,-3.13,-0.91,-1.09,-1.99,-1.74,-1.22,-0.92,-1.54,-1.03,-1.74
25%,-0.87,-0.87,-0.87,-0.69,-0.91,-1.09,-0.66,-0.70,-1.22,-0.92,-1.54,-1.03,-0.85
50%,0.00,0.00,0.03,0.01,0.30,0.91,-0.18,-0.00,0.33,-0.92,0.65,0.97,0.00
75%,0.86,0.87,0.87,0.70,0.30,0.91,0.49,0.69,0.82,0.81,0.65,0.97,0.85
max,1.73,1.74,1.69,2.06,1.51,0.91,5.05,1.73,2.80,4.26,0.65,0.97,1.73

### MIN MAX SCALER -> MIN_VAL = 0, MAX_VAL = 1

In [57]:
from sklearn.preprocessing import MinMaxScaler

In [58]:
mn = MinMaxScaler()

In [59]:
x_train_mn = mn.fit_transform(x_train)

In [60]:
x_train_new = pd.DataFrame(x_train_mn, columns = x_train.columns)

In [61]:
np.round(x_train_new.describe(),2)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
count,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00
mean,0.50,0.50,0.51,0.60,0.38,0.55,0.28,0.50,0.30,0.18,0.70,0.51,0.50
std,0.29,0.29,0.29,0.19,0.41,0.50,0.14,0.29,0.25,0.19,0.46,0.50,0.29
min,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,0.25,0.25,0.26,0.47,0.00,0.00,0.19,0.30,0.00,0.00,0.00,0.00,0.26
50%,0.50,0.50,0.52,0.61,0.50,1.00,0.26,0.50,0.38,0.00,1.00,1.00,0.50
75%,0.75,0.75,0.76,0.74,0.50,1.00,0.35,0.70,0.51,0.33,1.00,1.00,0.75
max,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00