# DAY 6

### Encoding - transform categorical data into numerical data

1. Label Encoder -> 1-1 column encode
2. Ordinal Encoder -> we can encode more than 2 cols with respect to their sub categories.
3. OneHotEncoder -> create new column based on the sub categories. it doesnt have col name, shows only values without col names.
4. Get Dummies (Pandas) -> Create new col based on sub categories but it has col name also

In [1]:
import numpy as np 
import pandas as pd

### 2. Ordinal Encoder

In [19]:
df = pd.read_csv('day 6 data\\covid_toy.csv')
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [20]:
df = df.drop(columns=["age","fever",'city'])

In [21]:
df.head(2)

  gender cough has_covid
0   Male  Mild        No
1   Male  Mild       Yes

In [15]:
df['gender'].value_counts()

gender
Female    59
Male      41
Name: count, dtype: int64

In [16]:
df['has_covid'].value_counts()

has_covid
No     55
Yes    45
Name: count, dtype: int64

In [17]:
from sklearn.preprocessing import OrdinalEncoder

In [22]:
oe = OrdinalEncoder(categories = [['Male','Female'],
                    ['Mild','Strong'],
                    ['Yes','No']])

In [23]:
oe

OrdinalEncoder(categories=[['Male', 'Female'], ['Mild', 'Strong'],
                           ['Yes', 'No']])

In [24]:
df_oe = oe.fit_transform(df) ## fit means to learn the categories and transform means to apply the encoding

In [25]:
df_new = pd.DataFrame(df_oe, columns = df.columns)

In [28]:
df_new.head()

   gender  cough  has_covid
0     0.0    0.0        1.0
1     0.0    0.0        0.0
2     0.0    0.0        1.0
3     1.0    0.0        1.0
4     1.0    0.0        1.0

### OneHot Encoder
    ->has_covid(no,yes)-> has_covid_no, has_covid_yes

In [29]:
df = pd.read_csv('day 6 data\\covid_toy.csv')
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [30]:
df = df.drop(columns=["age","fever"])

In [31]:
df.head(2)

  gender cough     city has_covid
0   Male  Mild  Kolkata        No
1   Male  Mild    Delhi       Yes

In [32]:
from sklearn.preprocessing import OneHotEncoder

In [33]:
ohe = OneHotEncoder(drop = 'first', sparse_output=False,dtype=np.int32) ## drop = 'first' is used to avoid dummy variable trap and sparse_output=False is used to get the output in dense format

In [43]:
df_new= ohe.fit_transform(df[['gender','cough','has_covid','city']])

In [44]:
df_new

array([[1, 0, 0, 0, 1, 0],
       [1, 0, 1, 1, 0, 0],
       [1, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0, 0],
       [1, 1, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 1],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 1],
       [0, 1, 0, 0, 1, 0],
       [1, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 1, 0],
       [0, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 1, 1, 0, 0, 0],
       [1, 1, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0],
       [0, 1, 1, 0, 1, 0],
       [0, 0, 1, 1, 0, 0],
       [0, 1, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 1],
       [0, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 0],
       [1, 0, 0, 0, 1, 0],
       [0, 1, 1, 0, 0, 1],
       [1, 0, 1, 1, 0, 0],
       [1, 0, 0, 0, 1, 0],
       [0, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [1, 0, 1, 0, 0, 1],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 0],
       [0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0],
       [1, 0, 1, 0, 1, 0],
       [1, 0, 1, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [1, 1, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 1, 1, 0, 0],
       [0, 1, 1, 0, 1, 0],
       [0, 1, 1, 0, 0, 0],
       [1, 0, 1, 1, 0, 0],
       [0, 0, 1, 0, 0, 1],
       [0, 0, 1, 0, 0, 1],
       [1, 1, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 1],
       [0, 0, 1, 0, 1, 0],
       [0, 1, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 1],
       [0, 1, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 1, 0, 1, 0, 0],
       [0, 1, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [1, 1, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 0],
       [1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [1, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 1, 0],
       [0, 0, 1, 0, 0, 1],
       [1, 0, 0, 1, 0, 0],
       [1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 1],
       [0, 0, 1, 0, 0, 0],
       [1, 0, 1, 0, 0, 0],
       [1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [1, 1, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 0],
       [1, 0, 1, 1, 0, 0],
       [0, 1, 0, 0, 1, 0],
       [1, 0, 1, 0, 1, 0],
       [1, 1, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 1],
       [0, 1, 1, 0, 1, 0]], dtype=int32)

In [42]:
df_new =pd.DataFrame(df_new, columns = ohe.get_feature_names_out())
df_new.head()

,gender_Male,cough_Strong,has_covid_Yes,city_Delhi,city_Kolkata,city_Mumbai
0,1,0,0,0,1,0
1,1,0,1,1,0,0
2,1,0,0,1,0,0
3,0,0,0,0,1,0
4,0,0,0,0,0,1

In [39]:
df['has_covid'].value_counts()

has_covid
No     55
Yes    45
Name: count, dtype: int64

### GET DUMMIES

In [45]:
df = pd.read_csv('day 6 data\\covid_toy.csv')
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [62]:
df = df.drop(columns=["age","fever"])

AttributeError: 'function' object has no attribute 'drop'

In [63]:
df.head(2)

AttributeError: 'function' object has no attribute 'head'

In [ ]:
df = df.dropna()

In [55]:
df_new = pd.get_dummies(df,columns=['gender','cough','has_covid','city'] ,drop_first=True)

TypeError: object of type 'method' has no len()

In [59]:
df_new = pd.DataFrame(df_new,columns = df_new.columns)

In [64]:
df_new = df_new.astype(int)

In [65]:
df_new

    0  1  2  3  4  5
0   1  0  0  0  1  0
1   1  0  1  1  0  0
2   1  0  0  1  0  0
3   0  0  0  0  1  0
4   0  0  0  0  0  1
.. .. .. .. .. .. ..
95  0  0  0  0  0  0
96  0  1  1  0  1  0
97  0  0  0  0  0  0
98  0  1  0  0  0  1
99  0  1  1  0  1  0

[100 rows x 6 columns]