# Practise Encoding on a insuarance dataset

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("day 6 data\\insurance.csv")
df.head(2)

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523

1. Label Encoding

In [5]:
from sklearn.preprocessing import LabelEncoder

In [2]:
lb = LabelEncoder()

In [6]:
df['sex'] = lb.fit_transform(df['sex'])
df['smoker'] = lb.fit_transform(df['smoker'])
df['region'] = lb.fit_transform(df['region'])

In [7]:
df.head()

   age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       3  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         3       0       2   4449.46200
3   33    1  22.705         0       0       1  21984.47061
4   32    1  28.880         0       0       1   3866.85520

2. Ordinal Encoding

In [8]:
df = pd.read_csv("day 6 data\\insurance.csv")
df.head(2)

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523

In [10]:
from sklearn.preprocessing import OrdinalEncoder

In [11]:
df = df.drop(columns=["age","bmi",'children','charges'])

In [14]:
df.head()

      sex smoker     region
0  female    yes  southwest
1    male     no  southeast
2    male     no  southeast
3    male     no  northwest
4    male     no  northwest

In [13]:
df['region'].value_counts()

region
southeast    364
southwest    325
northwest    325
northeast    324
Name: count, dtype: int64

In [15]:
oe = OrdinalEncoder(categories = [['male','female'],
                    ['yes','no'],
                    ['southeast','southwest','northeast','northwest']])

In [16]:
df_oe = oe.fit_transform(df) ## fit means to learn the categories and transform means to apply the encoding

In [17]:
df_new = pd.DataFrame(df_oe, columns = df.columns)

In [18]:
df_new.head()

   sex  smoker  region
0  1.0     0.0     1.0
1  0.0     1.0     0.0
2  0.0     1.0     0.0
3  0.0     1.0     3.0
4  0.0     1.0     3.0

### ONE HOT ENCODING

In [19]:
df = pd.read_csv("day 6 data\\insurance.csv")
df.head(2)

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523

In [20]:
df = df.drop(columns=["age","bmi",'children','charges'])

In [21]:
df.head()

      sex smoker     region
0  female    yes  southwest
1    male     no  southeast
2    male     no  southeast
3    male     no  northwest
4    male     no  northwest

In [22]:
from sklearn.preprocessing import OneHotEncoder

In [23]:
ohe = OneHotEncoder(drop = 'first', sparse_output=False,dtype=np.int32) ## drop = 'first' is used to avoid dummy variable trap and sparse_output=False is used to get the output in dense format

In [24]:
df_new= ohe.fit_transform(df[['sex','smoker','region']])

In [25]:
df_new

array([[0, 1, 0, 0, 1],
       [1, 0, 0, 1, 0],
       [1, 0, 0, 1, 0],
       ...,
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 1, 1, 0, 0]], shape=(1338, 5), dtype=int32)

In [26]:
df_new =pd.DataFrame(df_new, columns = ohe.get_feature_names_out())
df_new.head()

   sex_male  smoker_yes  region_northwest  region_southeast  region_southwest
0         0           1                 0                 0                 1
1         1           0                 0                 1                 0
2         1           0                 0                 1                 0
3         1           0                 1                 0                 0
4         1           0                 1                 0                 0

4. GET DUMMIES ENCODING

In [27]:
df = pd.read_csv("day 6 data\\insurance.csv")
df.head(2)

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523

In [28]:
df = df.drop(columns=["age","bmi",'children','charges'])

In [29]:
df.head(2)

      sex smoker     region
0  female    yes  southwest
1    male     no  southeast

In [30]:
df_new = pd.get_dummies(df,columns=['sex','smoker','region',] ,drop_first=True)

In [31]:
df_new = df_new.astype(int)

In [32]:
df_new

,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,0,1,0,0,1
1,1,0,0,1,0
2,1,0,0,1,0
3,1,0,1,0,0
4,1,0,1,0,0
...,...,...,...,...,...
1333,1,0,1,0,0
1334,0,0,0,0,0
1335,0,0,0,1,0
1336,0,0,0,0,1
1337,0,1,1,0,0